apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelo-api-deployment
spec:
  replicas: 2 # Queremos 2 cópias rodando para alta disponibilidade
  selector:
    matchLabels:
      app: modelo-api
  template:
    metadata:
      labels:
        app: modelo-api
    spec:
      containers:
      - name: modelo-container
        # SUBSTITUA A LINHA ABAIXO COM SEU USERNAME DO DOCKER HUB
        image: welloliveira/meu-modelo:v2
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: modelo-api-service
spec:
  type: NodePort # Tipo de serviço para expor a porta na máquina local
  ports:
  - port: 80 # Porta interna do cluster
    targetPort: 8000 # Porta que a API FastAPI está usando
    nodePort: 30000 # Porta que será aberta na sua máquina (ex: localhost:30000)
  selector:
    app: modelo-api