name: CI/CD MLOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3

    # Etapa 1: Instalação e Teste (Garante que as dependências funcionam)
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependências de Teste
      run: pip install -r requirements.txt
      
    - name: Executar Teste Rápido de Treinamento
      run: python teste_rapido.py

    # Etapa 2: Construir e Enviar Imagem Docker (Continuous Delivery)
    
    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Construir e Enviar Imagem
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        #tags: ${{ secrets.DOCKER_USERNAME }}/meu-modelo:${{ github.sha }}
        tags: ${{ secrets.DOCKER_USERNAME }}/meu-modelo:v2
        
    - name: Imagem Criada com Sucesso
      #run: echo "Imagem Docker enviada para ${{ secrets.DOCKER_USERNAME }}/meu-modelo:${{ github.sha }}"
      run: echo "Imagem Docker enviada para ${{ secrets.DOCKER_USERNAME }}/meu-modelo:v2"